version: '1.0.0'

products:
  - id: auto
    name: Seguro Auto
    scope: autoMfe
    url: http://localhost:3002/remoteEntry.js
    enabled: true

  - id: home
    name: Seguro Residencial
    scope: homeMfe
    url: http://localhost:3001/remoteEntry.js
    enabled: true

  - id: life
    name: Seguro de Vida
    scope: lifeMfe
    url: http://localhost:3003/remoteEntry.js
    enabled: false
